import time
import util.prettyConsole

prettyConsole.console('log', 'Test1')
time.sleep(1)
prettyConsole.console('log', 'Test2')
time.sleep(1)
prettyConsole.console('log', 'Test3')
time.sleep(1)
prettyConsole.console('log', 'Test4')
time.sleep(1)
prettyConsole.console('log', 'Test5')
time.sleep(1)
prettyConsole.console('update', 'Tested')
time.sleep(1)
prettyConsole.console('update', 'Tested1')
time.sleep(1)
prettyConsole.console('update', 'Tested2')
time.sleep(1)
prettyConsole.console('update', 'Tested3')
time.sleep(1)
prettyConsole.console('log', 'Test6')
time.sleep(1)
prettyConsole.console('log', 'Test7')
time.sleep(1)
prettyConsole.console('log', 'Test8')
time.sleep(1)