#
# Converts submitted command string to a key command to "type" into a window
#
#

class CommandSanitize:
    
    def __init__(self):
        self._command = { 'a': 'a',
                        'b': 'b',
                        'c': 'c',
                        'd': 'd',
                        'e': 'e',
                        'f': 'f',
                        'g': 'g',
                        'h': 'h',
                        'i': 'i',
                        'j': 'j',
                        'k': 'k',
                        'l': 'l',
                        'm': 'm',
                        'n': 'n',
                        'o': 'o',
                        'p': 'p',
                        'q': 'q',
                        'r': 'r',
                        's': 's',
                        't': 't',
                        'u': 'u',
                        'v': 'v',
                        'w': 'w',
                        'x': 'x',
                        'y': 'y',
                        'z': 'z',
                        'A': 'A',
                        'B': 'B',
                        'C': 'C',
                        'D': 'D',
                        'E': 'E',
                        'F': 'F',
                        'G': 'G',
                        'H': 'H',
                        'I': 'I',
                        'J': 'J',
                        'K': 'K',
                        'L': 'L',
                        'M': 'M',
                        'N': 'N',
                        'O': 'O',
                        'P': 'P',
                        'Q': 'Q',
                        'R': 'R',
                        'S': 'S',
                        'T': 'T',
                        'U': 'U',
                        'V': 'V',
                        'W': 'W',
                        'X': 'X',
                        'Y': 'Y',
                        'Z': 'Z',
                        '0': '0',
                        '1': '1',
                        '2': '2',
                        '3': '3',
                        '4': '4',
                        '5': '5',
                        '6': '6',
                        '7': '7',
                        '8': '8',
                        '9': '9',
                        '!': '!',
                        '"': '"',
                        '#': '#',
                        '$': '$',
                        '%': '%',
                        '&': '&',
                        '\'': '\'',
                        '(': '(',
                        ')': ')',
                        '*': '*',
                        '+': '+',
                        ',': ',',
                        '-': '-',
                        '.': '.',
                        '/': '/',
                        ':': ':',
                        ';': ';',
                        '<': '<',
                        '=': '=',
                        '>': '>',
                        '?': '?',
                        '@': '@',
                        '[': '[',
                        '\\': '\\',
                        ']': ']',
                        '^': '^',
                        '_': '_',
                        '`': '`',
                        '{': '{',
                        '|': '|',
                        '}': '}',
                        '~': '~',
                        'tab': 'tab',
                        'enter': 'enter',
                        'esc': 'esc',
                        'space': 'space',
                        'pageup': 'pageup',
                        'pagedown': 'pagedown',
                        'end': 'end',
                        'home': 'home',
                        'left': 'left',
                        'up': 'up',
                        'right': 'right',
                        'down': 'down',
        }
    
    def convertCommand(self, command):
        #return command from dictionary. If it doesn't exist, return 'None'
        return self._command.get(command, None)